<?php
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Name $block */

/*
<?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->toHtml() ?>

For checkout/onepage/shipping.phtml:

<?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')
   ->setObject($block->getAddress())
   ->setFieldIdFormat('shipping:%s')
   ->setFieldNameFormat('shipping[%s]')
   ->toHtml() ?>
*/

$prefix = $block->showPrefix();
$middle = $block->showMiddlename();
$suffix = $block->showSuffix();
$useKana = $block->getConfig('use_kana');
$requireKana = $block->getConfig('require_kana');
$kanaType = $block->getConfig('kana_type');
?>
<?php if (($prefix || $middle || $suffix) && !$block->getNoWrap()): ?>
<div class="field required fullname <?= $block->escapeHtmlAttr($block->getContainerClassName()) ?>">
    <label for="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>" class="label">
        <span><?= $block->escapeHtml(__('Name')) ?></span>
    </label>
    <div class="control">
        <fieldset class="fieldset fieldset-fullname">
        <div class="fields">
<?php endif; ?>

    <?php if ($prefix): ?>
        <div class="field field-name-prefix<?php if ($block->isPrefixRequired()) echo ' required' ?>">
            <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>">
                <span><?= $block->escapeHtml($block->getStoreLabel('prefix')) ?></span>
            </label>

            <div class="control">
                <?php if ($block->getPrefixOptions() === false): ?>
                    <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                           name="<?= $block->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getObject()->getPrefix()) ?>"
                           title="<?= $block->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                           class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?>" <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?>>
                <?php else: ?>
                    <select id="<?= $block->escapeHtmlAttr($block->getFieldId('prefix')) ?>"
                            name="<?= $block->escapeHtmlAttr($block->getFieldName('prefix')) ?>"
                            title="<?= $block->escapeHtmlAttr($block->getStoreLabel('prefix')) ?>"
                            class="<?= $block->escapeHtmlAttr($block->getAttributeValidationClass('prefix')) ?>" <?php if ($block->isPrefixRequired()) echo ' data-validate="{required:true}"' ?> >
                        <?php foreach ($block->getPrefixOptions() as $_option): ?>
                            <option value="<?= $block->escapeHtmlAttr($_option) ?>"<?php if ($block->getObject()->getPrefix() == $_option): ?> selected="selected"<?php endif; ?>>
                                <?= $block->escapeHtml(__($_option)) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
        <div class="field field-name-lastname required">
            <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>">
                <span><?= $block->escapeHtml($block->getStoreLabel('lastname')) ?></span>
            </label>

            <div class="control">
                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('lastname')) ?>"
                       name="<?= $block->escapeHtmlAttr($block->getFieldName('lastname')) ?>"
                       value="<?= $block->escapeHtmlAttr($block->getObject()->getLastname()) ?>"
                       title="<?= $block->escapeHtmlAttr($block->getStoreLabel('lastname')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('lastname')) ?>" <?php if ($block->getAttributeValidationClass('lastname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
            </div>
        </div>
    <?php if ($middle): ?>
        <?php $isMiddlenameRequired = $block->isMiddlenameRequired(); ?>
        <div class="field field-name-middlename<?= $isMiddlenameRequired ? ' required' : '' ?>">
            <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>">
                <span><?= $block->escapeHtml($block->getStoreLabel('middlename')) ?></span>
            </label>

            <div class="control">
                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('middlename')) ?>"
                       name="<?= $block->escapeHtmlAttr($block->getFieldName('middlename')) ?>"
                       value="<?= $block->escapeHtmlAttr($block->getObject()->getMiddlename()) ?>"
                       title="<?= $block->escapeHtmlAttr($block->getStoreLabel('middlename')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('middlename')) ?>" <?= $isMiddlenameRequired ? ' data-validate="{required:true}"' : '' ?>>
            </div>
        </div>
    <?php endif; ?>
        <div class="field field-name-firstname required">
            <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>">
                <span><?= $block->escapeHtml($block->getStoreLabel('firstname')) ?></span>
            </label>

            <div class="control">
                <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('firstname')) ?>"
                       name="<?= $block->escapeHtmlAttr($block->getFieldName('firstname')) ?>"
                       value="<?= $block->escapeHtmlAttr($block->getObject()->getFirstname()) ?>"
                       title="<?= $block->escapeHtmlAttr($block->getStoreLabel('firstname')) ?>"
                       class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('firstname')) ?>" <?php if ($block->getAttributeValidationClass('firstname') == 'required-entry') echo ' data-validate="{required:true}"' ?>>
            </div>
        </div>
    <?php if ($suffix): ?>
        <div class="field field-name-suffix<?php if ($block->isSuffixRequired()) echo ' required' ?>">
            <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>">
                <span><?= $block->escapeHtml($block->getStoreLabel('suffix')) ?></span>
            </label>

            <div class="control">
                <?php if ($block->getSuffixOptions() === false): ?>
                    <input type="text" id="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                           name="<?= $block->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getObject()->getSuffix()) ?>"
                           title="<?= $block->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                           class="input-text <?= $block->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>" <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>>
                <?php else: ?>
                    <select id="<?= $block->escapeHtmlAttr($block->getFieldId('suffix')) ?>"
                            name="<?= $block->escapeHtmlAttr($block->getFieldName('suffix')) ?>"
                            title="<?= $block->escapeHtmlAttr($block->getStoreLabel('suffix')) ?>"
                            class="<?= $block->escapeHtmlAttr($block->getAttributeValidationClass('suffix')) ?>" <?php if ($block->isSuffixRequired()) echo ' data-validate="{required:true}"' ?>>
                        <?php foreach ($block->getSuffixOptions() as $_option): ?>
                            <option value="<?= $block->escapeHtmlAttr($_option) ?>"<?php if ($block->getObject()->getSuffix() == $_option): ?> selected="selected"<?php endif; ?>>
                                <?= $block->escapeHtml(__($_option)) ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

    <?php if($useKana):?>
        <?php $rule = [] ;?>
        <?php if($requireKana): ?>
            <?php $rule[] = 'required:true';?>
        <?php endif;?>
        <?php if($kanaType == '1'): ?>
            <?php $rule[] = "'validate-katakana':true";?>
        <?php elseif($kanaType == '2'): ?>
            <?php $rule[] = "'validate-hiragana':true";?>
        <?php else: ?>
            <?php $rule[] = "'validate-kana':true";?>
        <?php endif;?>
        <?php $rule = join(',', $rule);?>
        <div class="field name lastname <?php if($requireKana):?>required<?php endif;?>">
            <label class="label"  for="<?= /* @escapeNotVerified */ $block->getFieldId('lastnamekana') ?>">
                <span><?= /* @escapeNotVerified */ $block->getStoreLabel('lastnamekana') ?></span>
            </label>

            <?php $attrLnameKana = $block->getObject()->getCustomAttribute('lastnamekana');?>
            <?php $lnameKana = '';?>
            <?php if(!is_null($attrLnameKana) && is_object($attrLnameKana)) :?>
                <?php $lnameKana = $attrLnameKana->getValue();?>
            <?php elseif(is_object($block->getObject())) :?>
                <?php if(method_exists($block->getObject(), 'getLastnamekana')):?>
                    <?php $lnameKana = $block->getObject()->getLastnamekana();?>
                <?php elseif (method_exists($block->getObject(), '__toArray') && array_key_exists('lastnamekana', $block->getObject()->__toArray())): ?>
                    <?php $lnameKana = $block->getObject()->getLastnamekana(); ?>
                <?php endif;?>
            <?php endif; ?>

            <div class="control">
                <input type="text" id="<?= /* @escapeNotVerified */ $block->getFieldId('lastnamekana') ?>"
                       name="<?= /* @escapeNotVerified */ $block->getFieldName('lastnamekana') ?>"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($lnameKana) ?>"
                       title="<?= /* @escapeNotVerified */ $block->getStoreLabel('lastnamekana') ?>"
                       class="input-text <?= /* @escapeNotVerified */ $block->getAttributeValidationClass('lastnamekana') ?>" <?= /* @escapeNotVerified */ $block->getFieldParams() ?>
                       <?php if ($rule): ?>data-validate="{<?= /* @escapeNotVerified */ $rule; ?>}"<?php endif; ?>>
            </div>
        </div>
        <div class="field name firstname <?php if($requireKana):?>required<?php endif;?>">
            <label class="label" for="<?= /* @escapeNotVerified */ $block->getFieldId('firstnamekana') ?>">
                <span><?= /* @escapeNotVerified */ $block->getStoreLabel('firstnamekana') ?></span>
            </label>

            <?php $attrFnameKana = $block->getObject()->getCustomAttribute('firstnamekana');?>
            <?php $fnameKana = '';?>
            <?php if(is_object($attrFnameKana)) :?>
                <?php $fnameKana = $attrFnameKana->getValue();?>
            <?php elseif(is_object($block->getObject())) :?>
                <?php if(method_exists($block->getObject(), 'getFirstnamekana')):?>
                    <?php $fnameKana = $block->getObject()->getFirstnamekana();?>
                <?php elseif (method_exists($block->getObject(), '__toArray') && array_key_exists('firstnamekana', $block->getObject()->__toArray())): ?>
                    <?php $fnameKana = $block->getObject()->getFirstnamekana(); ?>
                <?php endif;?>
            <?php endif; ?>
            <div class="control">
                <input type="text" id="<?= /* @escapeNotVerified */ $block->getFieldId('firstnamekana') ?>"
                       name="<?= /* @escapeNotVerified */ $block->getFieldName('firstnamekana') ?>"
                       value="<?= /* @escapeNotVerified */ $block->escapeHtml($fnameKana) ?>"
                       title="<?= /* @escapeNotVerified */ $block->getStoreLabel('firstnamekana') ?>"
                       class="input-text <?= /* @escapeNotVerified */ $block->getAttributeValidationClass('firstnamekana') ?>" <?= $block->getFieldParams() ?>
                       <?php if ($rule): ?>data-validate="{<?= /* @escapeNotVerified */ $rule; ?>}"<?php endif; ?>>
            </div>
        </div>
    <?php endif;?>
            <?php if (($prefix || $middle || $suffix) && !$block->getNoWrap()): ?>
        </div>
        </fieldset>
    </div>
</div>
<?php endif; ?>
