<?php
/**
 * Edit customer address template
 *
 * @var \Magento\Customer\Block\Address\Edit $block
 */

/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $this->helper(\Magento\Customer\Helper\Address::class);


/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $this->helper(\Magento\Directory\Helper\Data::class);
?>
<form class="form-address-edit"
      action="<?= $block->escapeUrl($block->getSaveUrl()) ?>"
      method="post" id="form-validate"
      enctype="multipart/form-data"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Contact Information')) ?></span></legend><br>
        <?= $block->getBlockHtml('formkey') ?>
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getLayout()
            ->createBlock(\Magento\Customer\Block\Widget\Name::class)
            ->setTemplate('MagentoJapan_Kana::customer/widget/jpname.phtml')
            ->setObject($block->getAddress())->toHtml()
        ?>
        <div class="field company">
            <label class="label" for="company"><span><?= $block->escapeHtml(__('Company')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="company"
                       id="company"
                       title="<?= $block->escapeHtmlAttr(__('Company')) ?>"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getCompany()) ?>"
                       class="input-text
                       <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('company')) ?>"
                >
            </div>
        </div>
        <div class="field telephone required">
            <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="telephone"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getTelephone()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       class="input-text
                       <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('telephone')) ?>"
                       id="telephone"
                >
            </div>
        </div>
        <div class="field fax">
            <label class="label" for="fax"><span><?= $block->escapeHtml(__('Fax')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="fax"
                       id="fax"
                       title="<?= $block->escapeHtmlAttr(__('Fax')) ?>"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getFax()) ?>"
                       class="input-text
                       <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('fax')) ?>"
                >
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= $block->escapeHtml(__('Address')) ?></span></legend><br>
        <?php if ($this->getConfig('localize/address/hide_country')) :?>
            <input type="hidden"
                   class="p-country-name"
                   name="country_id" value="<?= /* @noEscape */ $this->getConfig('general/country/default'); ?>"
                   id="country"
                   aria-required="true"
            />
        <?php else : ?>
        <div class="field country required">
            <label class="label" for="country"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
            <div class="control">
                <?= $block->getCountryHtmlSelect() ?>
            </div>
        </div>
        <?php endif; ?>
        <div class="field zip required">
            <label class="label" for="zip"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="postcode"
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getPostcode()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>"
                       id="zip"
                       class="input-text validate-zip-international
                       <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('postcode')) ?>"
                >
            </div>
        </div>
        <div class="field region required">
            <label class="label" for="region_id"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
            <div class="control">
                <select id="region_id"
                        name="region_id"
                        title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                        class="validate-select"
                        <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : ''; ?>
                >
                    <option value="">
                        <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                    </option>
                </select>
                <input type="text"
                       id="region"
                       name="region"
                       value="<?= $block->escapeHtmlAttr($block->getRegion()) ?>"
                       title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>"
                       class="input-text
                       <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('region')) ?>"
                       <?= (!$block->getConfig('general/region/display_all')) ? ' disabled="disabled"' : ''; ?>
                />
            </div>
        </div>
        <div class="field city required">
            <label class="label" for="city"><span><?= $block->escapeHtml(__('City')) ?></span></label>
            <div class="control">
                <input type="text" 
                       name="city" 
                       value="<?= $block->escapeHtmlAttr($block->getAddress()->getCity()) ?>" 
                       title="<?= $block->escapeHtmlAttr(__('City')) ?>" 
                       class="input-text
                       <?= $block->escapeHtmlAttr($addressHelper->getAttributeValidationClass('city')) ?>"
                       id="city"
                >
            </div>
        </div>

        <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>
        <div class="field street required">
            <label for="street_1" class="label"><span><?= $block->escapeHtml(__('Street Address')) ?></span></label>
            <div class="control">
                <input type="text"
                       name="street[]"
                       value="<?= $block->escapeHtmlAttr($block->getStreetLine(1)) ?>"
                       title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>"
                       id="street_1"
                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                />
                <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 1, $_n = $addressHelper->getStreetLines(); $_i < $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= $_i+1 ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i + 1)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text"
                                       name="street[]"
                                       value="<?= $block->escapeHtmlAttr($block->getStreetLine($_i + 1)) ?>"
                                       title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i + 1)) ?>"
                                       id="street_<?= $_i + 1 ?>"
                                       class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>"
                                >
                            </div>
                        </div>
                    <?php endfor; ?>
                </div>
            </div>
        </div>

        <?php if ($addressHelper->isVatAttributeVisible()) : ?>
            <div class="field taxvat">
                <label class="label" for="vat_id"><span><?= $block->escapeHtml(__('VAT Number')) ?></span></label>
                <div class="control">
                    <input type="text"
                           name="vat_id"
                           value="<?= $block->escapeHtmlAttr($block->getAddress()->getVatId()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('VAT Number')) ?>"
                           class="input-text <?= $block->escapeHtmlAttr(
                                   $addressHelper->getAttributeValidationClass('vat_id')
                           ) ?>"
                           id="vat_id"
                    >
                </div>
            </div>
        <?php endif; ?>
        <?php if ($block->isDefaultBilling()): ?>
            <div class="message info"><?= $block->escapeHtml(__("It's a default billing address.")) ?></div>
        <?php elseif ($block->canSetAsDefaultBilling()) : ?>
            <div class="field choice set billing">
                <input type="checkbox" id="primary_billing" name="default_billing" value="1" class="checkbox">
                <label class="label" for="primary_billing">
                    <span>
                        <?= $block->escapeHtml(__('Use as my default billing address')) ?>
                    </span>
                </label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_billing" value="1" />
        <?php endif; ?>

        <?php if ($block->isDefaultShipping()): ?>
            <div class="message info"><?= $block->escapeHtml(__("It's a default shipping address.")) ?></div>
        <?php elseif ($block->canSetAsDefaultShipping()) : ?>
            <div class="field choice set shipping">
                <input type="checkbox" id="primary_shipping" name="default_shipping" value="1" class="checkbox">
                <label class="label" for="primary_shipping">
                    <span><?= $block->escapeHtml(__('Use as my default shipping address')) ?></span>
                </label>
            </div>
        <?php else : ?>
            <input type="hidden" name="default_shipping" value="1">
        <?php endif; ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit"
                    class="action save primary"
                    data-action="save-address"
                    title="<?= $block->escapeHtmlAttr(__('Save Address')) ?>"
            >
                <span><?= $block->escapeHtml(__('Save Address')) ?></span>
            </button>
        </div>
        <div class="secondary">
            <a class="action back"href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $block->escapeHtml(__('Go back')) ?></span>
            </a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "validation": {}
        },
        "#country": {
            <?php if ($this->getConfig('localize/address/hide_country')):?>
            "jpRegionUpdater": {
        <?php else : ?>
            "regionUpdater": {
        <?php endif; ?>
                "optionalRegionAllowed": <?= $block->getConfig('general/region/display_all') ? 'true' : 'false'; ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= $block->escapeJs($directoryHelper->getRegionJson()) ?>,
                "defaultRegion": "<?= (int)$block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= $block->escapeJs($directoryHelper->getCountriesWithOptionalZip(true)) ?>
            }
        }
    }
</script>
