<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script type="text/x-magento-init">
    {
        "#zip" : {
            "CommunityEngineering_JapanesePostalCode/js/widget/address-updater" : {
                "regionId" : "#region_id",
                "region" : "#region",
                "city" : "#city",
                "street1" : "#street_1",
                "street2" : "#street_2"
            }
        }
    }
</script>
