<?php
/**
 * @var \MagentoJapan\Zip2address\Block\Customer $block
 */
?>
<script type="text/x-magento-init">
    {
        "#zip" : {
            "zip2address" : {
                "region" : "#region_id",
                "city" : "#city",
                "street" : "#street_1",
                "lang" : "<?= $block->escapeHtml($block->getCurrentLocale()) ?>"
            }
        }
    }
</script>
